AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}
  
  Sample SAM Template for {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        DATABASE_USER: ""
        DATABASE_PASSWORD: ""
        DATABASE_HOST: ""
        DATABASE_PORT: ""
        DATABASE_NAME: ""
        PAGINATOR_LIMIT_DEFAULT: ""
        DATABASE_MIGRATE: ""

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Beeblogit interaction AGW
      StageName: Prod

  StoreComment:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Create a comment
      CodeUri: cmd/comment/
      Handler: store
      Runtime: provided.al2
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /comments
            Method: POST
    Metadata:
        BuildMethod: go1.x

  GetComment:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Create a comment
      CodeUri: cmd/comment/
      Handler: getall
      Runtime: provided.al2
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /comments
            Method: GET
    Metadata:
      BuildMethod: go1.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StoreComment:
    Description: "First Lambda Function ARN"
    Value: !GetAtt StoreComment.Arn