name: deploy

on:
  push:
    branches:
      - qa
      - main
    tags:
      - "**"
jobs:
  deploy:
    uses: ncostamagna/github-workflows-templates/.github/workflows/go-serverless-deploy.yml@main
    secrets: inherit
